### PR TITLE
Add get_parse and get_parse_or generic over return T getters

### LINKED ISSUE #26: Get and parse to a generic T inferred from return T
### Feature Description
A function to access and parse into any type T or error out.

### Describe The Solution You'd Like
A function `envmnt::get<T>() -> Result<T, ?> where T: FromStr<T>`. This way a environment variable can be gotten and parsed by its return type, or gracefully error out. 

### Code Sample
```rust
pub fn get<T, E>(key: &'static str) -> EnvmtResult<T>
    where T: std::str::FromStr + std::str::FromStr<Err=E>,
          E: std::fmt::Display
{
    let var = std::env::var(key)
        .map_err(|e|
            EnvmtError::Missing(format!("Failed to load environment variable: '{}' ({})", name, e))
        )?;

    let val = var.parse::<T>()
        .map_err(|e|
            EnvmtError::InvalidType(
                format!("Failed to parse environment variable: '{}' to type '{}' ({})", name, stringify!(T), e)
            )
        )?;

    Ok(val)
}
```

### Collateral Effects

For instance numeric.rs can be simplified by this, since this generic specializes amongst other things into all its variants.

### Motivation

I'm currently carrying this boiler plate around project after project, so I figured it might be useful to upstream it into an existing env utilities crate like yours. Would you accept a pull request for something like this?

### PR DESCRIPTION
**Pull request by lweberk**
Closes #26

### CODE REVIEW

**Comment by sagiegurari** [comment]
@lweberk this is really great. can you also add tests please?
would love to see tests for various format types + errors.

**Comment by lweberk** [comment]
Sure thing. Just let me figure out the codecov pipeline/machinery. I'm a little bewildered by it. It is showing things as new (numeric.rs, bulk.rs, ...) that are not. Not showing things it should (generic.rs) and showing things it should not (error.rs)

**Comment by sagiegurari** [comment]
i don't care about coverage, just basic tests. so lets have generic_test.rs for that like in other modules.

**Comment by lweberk** [comment]
Perhaps some docs under usage as well?

**Comment by sagiegurari** [comment]
that would help. thanks

**Comment by lweberk** [comment]
Ok, there we go

**Comment by sagiegurari** [comment]
looks great. going to merge this in.
i'll probably update some examples and do minor cosmetic stuff..... there is another api i'm going to add (unreleated) and i'll release a new version.
thanks a lot!!!

**Pull request merged**
